# Generated by Django 4.2.23 on 2025-09-02 01:00

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='uploads/original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'tiff'])])),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to='uploads/compressed/')),
                ('watermark_removed_image', models.ImageField(blank=True, null=True, upload_to='uploads/watermark_removed/')),
                ('compress_image', models.BooleanField(default=False)),
                ('remove_watermark', models.BooleanField(default=False)),
                ('compression_quality', models.IntegerField(default=85, help_text='Quality percentage (1-100)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('compressed_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
